### ISSUE TITLE
Captcha unsolvable

### ISSUE THREAD

**Issue by JoahTheron** [Furry/2captcha#1]
Hey,

I am currently having an issue with using your great work. I tried to use your example which worked perfectly but after I have changed it to my website i would like to solve it nearly always stucks in an infinity loop or i get this error:

```
{"status":0,"request":"ERROR_CAPTCHA_UNSOLVABLE"}
APIError: An Unexpected Error has occured. Please submit an issue on GitHub detailing this event.
    at Solver.pollResponse (C:\GitProjects\DS_Timer_JS\node_modules\2captcha\dist\structs\2captcha.js:94:19)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Minion.solveCaptcha (C:\GitProjects\DS_Timer_JS\minion.js:41:3)
    at async Minion.place (C:\GitProjects\DS_Timer_JS\minion.js:87:5)
    at async process.<anonymous> (C:\GitProjects\DS_Timer_JS\schedule.js:23:11) {
  err: '{"status":0,"request":"ERROR_CAPTCHA_UNSOLVABLE"}',
  code: 0
}
```

6Ld2sf4SAAAAAKSgzs0Q13IZhY02Pyo31S2jgOB5
https://de178.die-staemme.de/game.php?village=1&screen=botcheck/

the 2 important informations.

**Comment by JoahTheron** [comment]
Problem solved.

**Comment by Furry** [comment]
> Problem solved.

Hiya there! Seems I didn't add a case for captcha unsolvable error, I'll get right on that.

What did you do to resolve the issue?

**Comment by JoahTheron** [comment]
The key was the issue. The website changed the Googlekey and i didn't notice it.
